package CPSC482Team.DSM;

import java.util.ArrayList;

/**
 * The name of this class is short for FeedBack Distance Optimizer, it contains a single
 * public method called {@Code optimize} which runs the greedy algorithm specified in the for 
 * minimizing the distance of feedback marks from the diagonal. It outputs a permutation which can
 * be fed to {@Code permute} in the {@Code DSMUtils} class
 */
public final class FBDOptimizer 
{
    /**
     * Takes a DSM matrix and returns a permutation with the distance of feedback marks from the 
     * diagonal optimized using the greedy algorithm specified in the report.
     *
     * @param g The DSM Matrix/Graph
     *
     * @return The optimized perumtation
     */
    public static int[] optimize(DSMMatrix g) {
        int n = g.n;

        // First take note of the distance of feedback and feedforward marks from the diagonal 
        // for each row in the matrix
        ArrayList<ArrayList<Integer>> feedbackDistances = new ArrayList<ArrayList<Integer>>();
        ArrayList<ArrayList<Integer>> feedforwardDistances = new ArrayList<ArrayList<Integer>>();

        generateLists(g, feedbackDistances, feedforwardDistances);

        int[] result = optimizeLists(n, feedbackDistances, feedforwardDistances);
        return result;
    }

    /// Takes the lists generated by generate lists (along with the size of the matrix) 
    /// and uses them to create an optimized permutation
    private static int[] optimizeLists(int n,
        ArrayList<ArrayList<Integer>> feedbackDistances, 
        ArrayList<ArrayList<Integer>> feedforwardDistances) {

        // feedbackDistances is sorted, feedforwardDistances is reverse sorted
        
        int[] resultingPerutation = new int[n];
        
        // fill the base permutation with the numbers 0...n-1
        for (int i = 0; i < n; i++) {
            resultingPerutation[i] = i;
        }

        // For each vertex, compare the lists to see if any position adjustments can be made.
        for (int i = 0; i < n; i++) {
            // Short for feed forward distance index and feed backward distance index respectively
            int fFDIndex = 0;
            int fBDIndex = 0;

            ArrayList<Integer> currentFFDistances = feedforwardDistances.get(i);
            ArrayList<Integer> currentFBDistances = feedbackDistances.get(i);

            int currentVertex = i; // also the current column and current row
            
            // Start both vertices at the current column
            int currentFFColumn = currentVertex;
            int currentFBColumn = currentVertex;

            // Go through both lists and run main part of the algorithm
            while (fFDIndex < currentFFDistances.size() && fBDIndex < currentFBDistances.size()) {
                // Get largest distances
                // names is short for largest feed forward distance and largest feed back distance respectively
                
                assert((currentFFDistances.size() - 1 - fFDIndex) < (currentFFDistances.size()));
                assert((currentFFDistances.size() - 1 - fFDIndex) >= 0);
                assert(fBDIndex >= 0);
                assert(fBDIndex < currentFBDistances.size());

                int largestFFD = currentFFDistances.get(currentFFDistances.size() - 1 - fFDIndex);
                int largestFBD = currentFBDistances.get(fBDIndex);

                if (largestFBD > largestFFD) {
                    // Adjust distances as needed
                    currentFFColumn -= largestFFD;
                    currentFBColumn += largestFBD;
                    break;
                }
                else if (largestFBD <= largestFFD && (currentFBDistances.size() - 1) < fBDIndex) {
                    fBDIndex++;
                }
                else if (largestFBD <= largestFFD && (currentFBDistances.size() - 1) == fBDIndex) {
                    fFDIndex++;
                }
            }

            // Now swap the vertices
            int tmp = resultingPerutation[currentFFColumn];
            resultingPerutation[currentFFColumn] = currentFBColumn;
            resultingPerutation[currentFBColumn] = tmp;
        }

        return resultingPerutation;
    }

    // Takes two empty Arraylists and the matrix and populates them with the distances
    // of marks from the diagonal populating feedbackDistances with the distances for
    // feedback marks and feedforwardDistances with the distances for feedforward marks
    private static void generateLists(DSMMatrix g, 
        ArrayList<ArrayList<Integer>> feedbackDistances, 
        ArrayList<ArrayList<Integer>> feedforwardDistances) {

        int[] colPtr = g.colPtr;
        int[] rowInd = g.rowInd;
        int n = g.n;

        for (int i = 0; i < n; i++) {
            feedbackDistances.add(new ArrayList<Integer>());
            feedforwardDistances.add(new ArrayList<Integer>());
        }
        
        assert(feedforwardDistances.size() == n);
        assert(feedbackDistances.size() == n);

        // Use the loops to constuct to convert the matrix from compressed sparse column
        // to a more manageable format for each iteration.
        for (int i = 0; i < n; i++) {
            for (int j = colPtr[i]; j < colPtr[i + 1]; j++) {
                int currentRow = rowInd[j];
                int currentColumn = i;
                
                // Calculate distances from the diagonal 
                int diagColumn = currentRow; // Matrix is square

                if (currentColumn > diagColumn) {
                    int distance = currentColumn - diagColumn;
                    feedbackDistances.get(currentRow).add(distance);
                }
                // i < diagColumn
                else {
                    int distance = diagColumn - currentColumn;
                    feedforwardDistances.get(currentRow).add(distance);
                }
            }
        }
    }
}
